### ISSUE TITLE
Missing responsive styles

### ISSUE THREAD

**Issue by jorge-autogravity** [vickeetran/AutoGravity-Calculator#1]
Hi Victoria, I was testing your app and noticed that it isn't responsive to different screen sizes

**Comment by hellofromv** [comment]
Hi Jorge! I'm at work until 5pm today, but if you wouldn't mind waiting
until I get home, I can try to fix it then. I apologize for the
inconvenience.

**Comment by jorge-autogravity** [comment]
no problem!

**Comment by hellofromv** [comment]
Thank you! I'll get it to you as soon as possible :)

**Comment by hellofromv** [comment]
I fixed the resizing issue on desktop and mobile. Thanks for waiting!
